const compliments = [
  'Even if you were cloned, you\'d still be one of a kind. And the better looking one.',
  'It\'s not easy to be me. Which is why I need you.',
  'I would love to spend every minute of every day with you, but some days I actually have to get stuff done.',
  'Your smile is proof that the best things in life are free.',
  'You\'re smarter than Google and Mary Poppins combined.',
  'I think the hardest part about being your friend is pretending as though I like my other friends as much as I like you.',
  'You\'re not someone I pretend to not see in public.',
  'I don\'t have a favourite colour, It\'s pretty much whatever you are wearing.',
  'I can never remember my dreams, but I assume you are always in them.',
  'You are like a corner piece of a puzzle. Without you, I\'m completely lost.',
  'If the last two people on earth were us, I would have no problem repopulating it with you.',
  'Out of all my friends you are the best at being single.',
  'You inspire me and most likely strangers. Also, friends and stalkers. You are the inspiration to many.',
  'I don\'t know if sarcasm is a skill, but you\'ve certainly mastered it.',
  'If you knew how much I think about you, I would be very embarrassed.',
  'You are so beautiful I would certainly steal your photos, make a fake account and impress people online.',
  'You\'re just as pretty as all the layers you hide behind.',
  'Your face makes other people ugly.',
  'I can\'t take my eyes off of you. Unless you notice me, then I\'ll quickly look away and act like it never happened.',
  'Are you a beaver, because damn.',
  'You\'re like the one sock that dissapears. I don\'t know what I did to lose you but I want you back.',
  'If it was legal to marry food, I would still choose you over pizza.',
  'You might be the primary reason for global warming.',
  'I bet you make babies smile.',
  'If there is one thing I like about you, its that I like more than one thing about you.',
  'You have that kind of body that when others see it they realise they need to workout more.',
  'You are more unique and wonderful than the smell of a new book.',
  'The person who raised you deserves a medal for a job well done.',
  'Did you have plastic surgery to become that attractive?',
  'I\'m not drunk, just intoxicated by you.',
  "Talking to you is the best part of my day, aside from when I'm sleeping and when I'm eating.",
  'For someone who has given birth, you look pretty good!',
  "You're the nothing when people ask me whats on my mind.",
  'You are awkward, in a cute way. Like an elevator ride, but with puppies.',
  'It\'s too bad you don\'t see what I see, if you did you\'d smile and keep looking.',
  'You may not be really, really good looking. But you\'re pretty damn close.',
  'Just like an untrained puppy. I\'d really like to take you out.',
  'You know what\'s awesome? Chocolate cake, oh and your face.',
  'I\'m not insulting you, I\'m describing you.',
  'Maybe you should eat some makeup so you can be pretty on the inside too.',
  'Our time together is like a nap, it just doesn\'t last long enough.',
  'Every day without you is like a day without my phone, I just don\'t know what to do with myself.',
  'I\'m really good at people-watching. I\'m so glad I can share that hobby on you.',
  'You make everything better. If people were more like you the world would be perfect.',
  'You\'re not lazy, just that the people around you are way too active.',
];

export default compliments;
